controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# ROUTES:

page_home:
    path: /
    controller: App\Controller\PageController::home
    methods: ['GET']
    
page_view_article:
    path: /article/{id}
    controller: App\Controller\PageController::viewArticle
    methods: ['GET']
   
page_checkout:
    path: /checkout
    controller: App\Controller\PageController::checkout
    methods: ['GET']
   
page_view_product_by_id:
    path: /product-id/{id}
    controller: App\Controller\PageController::viewProductById
    methods: ['GET']
    
page_view_product_by_slug:
    path: /product/{slug}
    controller: App\Controller\PageController::viewProductBySlug
    methods: ['GET']
    
page_view_article_fetch: #fetch post via POST after 
    path: /article-view/{id}
    controller: App\Controller\PageController::viewArticleFetch
    methods: ['GET']

page_demo_product:
    path: /product-demo
    controller: App\Controller\PageController::demoProduct
    methods: ['GET']
    
page_demo_product_list:
    path: /product-list-demo
    controller: App\Controller\PageController::demoProductList
    methods: ['GET']
  
    
page_demo_product_checkout:
    path: /product-checkout-demo
    controller: App\Controller\PageController::demoProductCheckout
    methods: ['GET']
  
    
page_demo_shopping_cart:
    path: /shopping-cart-demo
    controller: App\Controller\PageController::demoShoppingCart
    methods: ['GET']
    
page_product_list:
    path: /product-list
    controller: App\Controller\PageController::productList
    methods: ['GET']
   
#page_product_category_url_list:
#    path: /products/{path}
#    controller: App\Controller\PageController::productList
#    methods: ['GET']
#    requirements:
#        path: "[a-zA-Z0-9\-/]+"
# this one is for /products/my-cat-one/my-cat-two/my-cat-three
# $segments = explode('/', $path);
   
page_about:
    path: /about
    controller: App\Controller\PageController::about
    methods: ['GET']

user_login_get:
    path: /user/login
    controller: App\Controller\UserController::loginGet
    methods: ['GET']
    
user_login_post:
    path: /user/login
    controller: App\Controller\UserController::loginpost
    methods: ['POST']
    
user_register_get:
    path: /user/register
    controller: App\Controller\UserController::registerGet
    methods: ['GET']
        
user_register_post:
    path: /user/register
    controller: App\Controller\UserController::registerPost
    methods: ['POST']
    
user_logout_get:
    path: /user/logout
    controller: App\Controller\UserController::logoutGet
    methods: ['GET']

article_post_id:
    path: /article-get-by-id/{id}
    controller: App\Controller\ArticleController::getByIdPost 
    methods: ['POST']

article_post_get_all: 
    path: /article-get-all
    controller: App\Controller\ArticleController::getArticlesPost 
    methods: ['GET']
    # queryparams: page, per_page, sort: id-asc, id-desc, asc, desc

article_create: 
    path: /article-create
    controller: App\Controller\ArticleController::createPost 
    methods: ['POST']

article_edit: 
    path: /article-edit
    controller: App\Controller\ArticleController::updatePost 
    methods: ['POST']

article_delete:
    path: /article-delete
    controller: App\Controller\ArticleController::deleteArticleByIdPost
    methods: ['POST']
 
article_delete_by_ids:
    path: /article-delete-by-ids
    controller: App\Controller\ArticleController::deleteByIdsPost
    methods: ['POST']
    
article_remove_categories_by_ids:
    path: /remove-categories-by-ids
    controller: App\Controller\ArticleController::removeArticleCategoryLinksPost
    methods: ['POST']
    
article_get_category_and_tag_ids:
    path: /get-article-categories-and-tags/{id}
    controller: App\Controller\ArticleController::getArticleCategoryAndTagIds
    methods: ['GET']  
    
dashboard_home:
    path: /dashboard
    controller: App\Controller\DashboardController::index
    methods: ['GET']
    
dashboard_articles:
    path: /dashboard/articles
    controller: App\Controller\DashboardController::articles
    methods: ['GET']
    
dashboard_article_create: 
    path: /dashboard/article-create
    controller: App\Controller\DashboardController::createArticle 
    methods: ['GET']

dashboard_article_edit: 
    path: /dashboard/article-edit/{id}
    controller: App\Controller\DashboardController::editArticle 
    methods: ['GET']

dashboard_product_create:
    path: /dashboard/product-create
    controller: App\Controller\DashboardController::createProduct
    methods: ['GET']

dashboard_categories: 
    path: /dashboard/categories
    controller: App\Controller\DashboardController::categories 
    methods: ['GET']

dashboard_tags: 
    path: /dashboard/tags
    controller: App\Controller\DashboardController::tags 
    methods: ['GET']
    
dashboard_tag_create: 
    path: /dashboard/tag-create
    controller: App\Controller\DashboardController::createTag
    methods: ['GET']
    
dashboard_product_tag_create: 
    path: /dashboard/product-tag-create
    controller: App\Controller\DashboardController::createProductTag
    methods: ['GET']
    
dashboard_tag_edit: 
    path: /dashboard/tag-edit/{id}
    controller: App\Controller\DashboardController::editTag 
    methods: ['GET']

dashboard_files: 
    path: /dashboard/files
    controller: App\Controller\DashboardController::files 
    methods: ['GET']
    
dashboard_images: 
    path: /dashboard/images
    controller: App\Controller\DashboardController::images 
    methods: ['GET']
    
dashboard_images_edit: 
    path: /dashboard/images-edit/{slug}
    controller: App\Controller\DashboardController::editImages 
    methods: ['GET']
    
dashboard_files_edit: 
    path: /dashboard/files-edit/{slug}
    controller: App\Controller\DashboardController::editFiles 
    methods: ['GET']
    
dashboard_category_edit: 
    path: /dashboard/category-edit/{id}
    controller: App\Controller\DashboardController::editCategory 
    methods: ['GET']

dashboard_category_create: 
    path: /dashboard/category-create
    controller: App\Controller\DashboardController::createCategory 
    methods: ['GET']
    
dashboard_product_category_create: 
    path: /dashboard/product-category-create
    controller: App\Controller\DashboardController::createProductCategory 
    methods: ['GET']  
     
dashboard_product_category_edit: 
    path: /dashboard/product-category-edit/{id}
    controller: App\Controller\DashboardController::editProductCategory 
    methods: ['GET']
     
dashboard_product_edit: 
    path: /dashboard/product-edit/{id}
    controller: App\Controller\DashboardController::editProduct 
    methods: ['GET']
     
dashboard_docs: 
    path: /dashboard/docs
    controller: App\Controller\DashboardController::docs 
    methods: ['GET']
  
dashboard_orders:
    path: /dashboard/orders
    controller: App\Controller\DashboardController::orders
    methods: ['GET']
  
dashboard_products:
    path: /dashboard/products
    controller: App\Controller\DashboardController::products
    methods: ['GET']
   
dashboard_product_categories:
    path: /dashboard/product-categories
    controller: App\Controller\DashboardController::productCategories
    methods: ['GET']
   
dashboard_product_tags:
    path: /dashboard/product-tags
    controller: App\Controller\DashboardController::productTags
    methods: ['GET']
   
dashboard_product_attributes:
    path: /dashboard/product-attributes
    controller: App\Controller\DashboardController::productAttributes
    methods: ['GET']
   
dashboard_product_attributes_edit: 
    path: /dashboard/product-attributes-edit/{id}
    controller: App\Controller\DashboardController::editProductAttributes
    methods: ['GET']

dashboard_product_attribute_create: 
    path: /dashboard/product-attribute-create
    controller: App\Controller\DashboardController::createProductAttribute
    methods: ['GET']
   
dashboard_product_tag_edit: 
    path: /dashboard/product-tag-edit/{id}
    controller: App\Controller\DashboardController::editProductTag
    methods: ['GET']
    
dashboard_category_tree:
    path: /dashboard/product-category-tree
    controller: App\Controller\DashboardController::productCategoryTree 
    methods: ['GET']

category_create:
    path: /category-create
    controller: App\Controller\CategoryController::create
    methods: ['POST']

category_edit: 
    path: /category-edit
    controller: App\Controller\CategoryController::edit 
    methods: ['POST']

   
category_get_all: 
    path: /category-get-all
    controller: App\Controller\CategoryController::get 
    methods: ['GET']
    # queryparams: page, per_page, sort: id-asc, id-desc, asc, desc


category_get_all_products: 
    path: /product-category-get-all
    controller: App\Controller\CategoryController::getProducts 
    methods: ['GET']
    # queryparams: page, per_page, sort: id-asc, id-desc, asc, desc


category_get_by_ids: 
    path: /category-get-by-ids
    controller: App\Controller\CategoryController::getCategoriesByIds 
    methods: ['POST']
       
category_add_article_to_categories: 
    path: /add-article-to-categories
    controller: App\Controller\CategoryController::addArticleToCategories 
    methods: ['POST']

category_link_articles_to_categories: 
    path: /link-article-to-categories
    controller: App\Controller\CategoryController::linkArticlesToCategory 
    methods: ['POST']

# linkArticlesToCategory

tag_get_all: 
    path: /tag-get-all
    controller: App\Controller\TagController::get 
    methods: ['GET']
    
tag_edit: 
    path: /tag-edit
    controller: App\Controller\TagController::edit 
    methods: ['POST']
    
tag_create: 
    path: /tag-create
    controller: App\Controller\TagController::create 
    methods: ['POST']
 
tag_get_by_ids: 
    path: /tag-get-by-ids
    controller: App\Controller\TagController::getTagsByIds 
    methods: ['POST']
 
tag_add_article_to_tags: 
    path: /add-article-to-tags
    controller: App\Controller\TagController::addArticleToTags 
    methods: ['POST']
    
image_add: 
    path: /image-add
    controller: App\Controller\ImagesController::addImage
    methods: ['POST']

image_get_group: 
    path: /image-get-groups
    controller: App\Controller\ImagesController::getGroups
    methods: ['GET']
    
image_create_group: 
    path: /image-create-group
    controller: App\Controller\ImagesController::createGroupPost
    methods: ['POST']

image_get_group_images: 
    path: /image-get-group-images/{slug}
    controller: App\Controller\ImagesController::getGroupImages
    methods: ['GET']

image_upload: 
    path: /image-upload
    controller: App\Controller\ImagesController::upload
    methods: ['POST']

image_update_group_image_info: 
    path: /image-update-group-info
    controller: App\Controller\ImagesController::updateGroupInfoPost
    methods: ['POST']
    
image_delete_image: 
    path: /image-single-delete
    controller: App\Controller\ImagesController::deleteGroupImage
    methods: ['POST']
    
image_bulk_image: 
    path: /image-bulk-delete
    controller: App\Controller\ImagesController::deleteBulkImage
    methods: ['POST']
    
file_create_group: 
    path: /file-create-group
    controller: App\Controller\FilesController::createGroupPost
    methods: ['POST']
    
file_get_group: 
    path: /file-get-groups
    controller: App\Controller\FilesController::getGroups
    methods: ['GET']
    
file_get_group_files: 
    path: /file-get-group-files/{slug}
    controller: App\Controller\FilesController::getGroupFiles
    methods: ['GET']

file_upload: 
    path: /file-upload
    controller: App\Controller\FilesController::upload
    methods: ['POST']
    
file_delete_image: 
    path: /file-single-delete
    controller: App\Controller\FilesController::deleteGroupFile
    methods: ['POST']
    
file_bulk_image: 
    path: /file-bulk-delete
    controller: App\Controller\FilesController::deleteBulkFile
    methods: ['POST']    
    
product_create: 
    path: /product-create
    controller: App\Controller\ProductController::createPost 
    methods: ['POST']
    
product_update: 
    path: /product-update
    controller: App\Controller\ProductController::updatePost 
    methods: ['POST']

product_get_all: 
    path: /product-get-all
    controller: App\Controller\ProductController::getProducts
    methods: ['GET']
    # queryparams: page, per_page, sort: id-asc, id-desc, asc, desc

product_category_edit: 
    path: /product-category-edit
    controller: App\Controller\CategoryController::editProduct 
    methods: ['POST']


utils_generate_uuid:   
    path: /utils/generate-uuid
    controller: App\Controller\UtilsController::getUuid 
    methods: ['GET']


attribute_get_all: 
    path: /attribute-get-all
    controller: App\Controller\AttributeController::get 
    methods: ['GET']

attribute_get_by_article_id: 
    path: /attribute-get-by-article-id/{articleId}
    controller: App\Controller\AttributeController::getByArticleId
    methods: ['GET']
    
attribute_get_by_id: 
    path: /attribute-get-by-id/{id}
    controller: App\Controller\AttributeController::getById
    methods: ['GET'] 
      
attribute_create: 
    path: /attribute-create-multi
    controller: App\Controller\AttributeController::createMulti
    methods: ['POST']
      
attribute_get_by_slug:
    path: /attribute-get-by-slug/{slug}
    controller: App\Controller\AttributeController::getAttributesBySlug
    methods: ['GET']

orders_get_all: 
    path: /order-get-all
    controller: App\Controller\OrdersController::getAll
    methods: ['GET']
    
json_store_tree_data:
    path: /json-store-tree-data
    controller: App\Controller\JsonHandlerController::saveTreeData
    methods: ['POST']
