controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# ROUTES:

page_home:
    path: /
    controller: App\Controller\PageController::home
    methods: ['GET']
    
page_view_article:
    path: /article/{id}
    controller: App\Controller\PageController::viewArticle
    methods: ['GET']

page_about:
    path: /about
    controller: App\Controller\PageController::about
    methods: ['GET']

user_login_get:
    path: /user/login
    controller: App\Controller\UserController::loginGet
    methods: ['GET']
    
user_login_post:
    path: /user/login
    controller: App\Controller\UserController::loginpost
    methods: ['POST']
    
user_register_get:
    path: /user/register
    controller: App\Controller\UserController::registerGet
    methods: ['GET']
        
user_register_post:
    path: /user/register
    controller: App\Controller\UserController::registerPost
    methods: ['POST']
    
user_logout_get:
    path: /user/logout
    controller: App\Controller\UserController::logoutGet
    methods: ['GET']

article_post_id:
    path: /article-get-by-id/{id}
    controller: App\Controller\ArticleController::getByIdPost 
    methods: ['POST']

article_post_get_all: 
    path: /article-get-all
    controller: App\Controller\ArticleController::getArticlesPost 
    methods: ['GET']
    # queryparams: page, per_page, sort: id-asc, id-desc, asc, desc

article_create: 
    path: /article-create
    controller: App\Controller\ArticleController::createPost 
    methods: ['POST']

article_edit: 
    path: /article-edit
    controller: App\Controller\ArticleController::editPost 
    methods: ['POST']

article_delete:
    path: /article-delete
    controller: App\Controller\ArticleController::deleteArticleByIdPost
    methods: ['POST']
 
article_delete_by_ids:
    path: /article-delete-by-ids
    controller: App\Controller\ArticleController::deleteByIdsPost
    methods: ['POST']
    
article_remove_categories_by_ids:
    path: /remove-categories-by-ids
    controller: App\Controller\ArticleController::removeArticleCategoryLinksPost
    methods: ['POST']
    
article_get_category_and_tag_ids:
    path: /get-article-categories-and-tags/{id}
    controller: App\Controller\ArticleController::getArticleCategoryAndTagIds
    methods: ['GET']  
   
    
dashboard_home:
    path: /dashboard
    controller: App\Controller\DashboardController::index
    methods: ['GET']
    
dashboard_articles:
    path: /dashboard/articles
    controller: App\Controller\DashboardController::articles
    methods: ['GET']

dashboard_article_create: 
    path: /dashboard/article-create
    controller: App\Controller\DashboardController::createArticle 
    methods: ['GET']

dashboard_article_edit: 
    path: /dashboard/article-edit/{id}
    controller: App\Controller\DashboardController::editArticle 
    methods: ['GET']


dashboard_categories: 
    path: /dashboard/categories
    controller: App\Controller\DashboardController::categories 
    methods: ['GET']

dashboard_tags: 
    path: /dashboard/tags
    controller: App\Controller\DashboardController::tags 
    methods: ['GET']
    
dashboard_tag_create: 
    path: /dashboard/tag-create
    controller: App\Controller\DashboardController::createTag
    methods: ['GET']

dashboard_tag_edit: 
    path: /dashboard/tag-edit/{id}
    controller: App\Controller\DashboardController::editTag 
    methods: ['GET']

dashboard_files: 
    path: /dashboard/files
    controller: App\Controller\DashboardController::files 
    methods: ['GET']
    
dashboard_images: 
    path: /dashboard/images
    controller: App\Controller\DashboardController::images 
    methods: ['GET']
    
dashboard_category_edit: 
    path: /dashboard/category-edit/{id}
    controller: App\Controller\DashboardController::editCategory 
    methods: ['GET']

dashboard_category_create: 
    path: /dashboard/category-create
    controller: App\Controller\DashboardController::createCategory 
    methods: ['GET']

category_create:
    path: /category-create
    controller: App\Controller\CategoryController::create
    methods: ['POST']

category_edit: 
    path: /category-edit
    controller: App\Controller\CategoryController::edit 
    methods: ['POST']

   
category_get_all: 
    path: /category-get-all
    controller: App\Controller\CategoryController::get 
    methods: ['GET']
    # queryparams: page, per_page, sort: id-asc, id-desc, asc, desc
      
category_get_by_ids: 
    path: /category-get-by-ids
    controller: App\Controller\CategoryController::getCategoriesByIds 
    methods: ['POST']
          
tag_get_all: 
    path: /tag-get-all
    controller: App\Controller\TagController::get 
    methods: ['GET']
    
tag_edit: 
    path: /tag-edit
    controller: App\Controller\TagController::edit 
    methods: ['POST']
    
tag_create: 
    path: /tag-create
    controller: App\Controller\TagController::create 
    methods: ['POST']
 
tag_get_by_ids: 
    path: /tag-get-by-ids
    controller: App\Controller\TagController::getTagsByIds 
    methods: ['POST']
 
